# using packages - pandas

The pandas name itself is derived from panel data, an econometrics term for multidimensional
structured datasets, and a play on the phrase Python data analysis.

Pandas is used for creating and manipulating easy to use data structures, it also includes data analysis tools

The pandas library essentially has three data structures:

Series:
For one-dimensional array, of any type: integers, floats, strings, and Python

DataFrame
For 2D data structure with each column of any datatypes. 
DataFrame can be created from NumPy array, Lists, Dicts, pd.Series, A 2D NumPy array

Panel
A Panel is a data structure that handles 3D data

Data Frame: is a special data object, comparable to a spreadsheet
Data Frame is made up of rows and columns. Columns can be of different types. Within a column all rows are of same type.
Hence, a data frame can be visualized as a set of arrays.

create data frame reading data from files or using pandas Dataframe() on a set of arrays. 
Matrix is a 2D structure like data frame however all elements of a matrix are of the same type.

In [336]:
import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype

In [337]:
# enables display of outputs from all rows in a cell, not just the last statement
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Series

In [338]:
# series
# create empty
# add element
# drop element
# subset of elements
# display index
# change index
# show just values
# count of each unique value
# what are the unique values
# summary statistics
# plot


In [339]:
Seris = pd.Series()
Seris

C:\Users\Dell\AppData\Local\Temp\ipykernel_66152\2977403205.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  Seris = pd.Series()


Series([], dtype: float64)

In [340]:
Seris = pd.Series([1,2.9,3,4,11], index=[1,2,3,4,5])
Seris

1     1.0
2     2.9
3     3.0
4     4.0
5    11.0
dtype: float64

In [341]:
type(Seris)

pandas.core.series.Series

In [342]:
Seris, Seris.values, Seris.index

(1     1.0
 2     2.9
 3     3.0
 4     4.0
 5    11.0
 dtype: float64,
 array([ 1. ,  2.9,  3. ,  4. , 11. ]),
 Int64Index([1, 2, 3, 4, 5], dtype='int64'))

In [343]:
import pandas as pd

series1 = pd.Series([10, 20, 30], index=['Alice', 'Bob', 'Charlie'])
series2 = pd.Series([5, 15, 25], index=['Bob', 'Charlie', 'Dave'])

# matching indexes, if not found treats as NaN
print(series1 + series2)

# NaN given default value
print(series1.add(series2, fill_value=0))

Alice       NaN
Bob        25.0
Charlie    45.0
Dave        NaN
dtype: float64
Alice      10.0
Bob        25.0
Charlie    45.0
Dave       25.0
dtype: float64


In [344]:
seris = pd.Series(np.arange(2,10))
seris.mean()

5.5

# dataframe

In [345]:
# create pandas df from ndarrays

In [346]:
x_arr = np.array([1,2,3])
df = pd.DataFrame(x_arr)
df.columns = ['x']
df

,x
0,1
1,2
2,3


In [347]:
pd.DataFrame(x_arr, columns = ['x'])

,x
0,1
1,2
2,3


In [348]:
np.random.normal(size=6).reshape(3,2)

array([[ 1.87063925,  0.32856635],
       [-2.1001202 , -1.88692248],
       [-0.76894557,  1.57962916]])

In [349]:
pd.DataFrame(np.random.normal(size=10).reshape(5,2),columns=['x1','x2'])

,x1,x2
0,-0.061244,-1.407140
1,-0.175185,-1.249368
2,1.015829,0.390493
3,0.968820,-0.355254
4,1.392840,0.059511


In [350]:
# initiate a dictionary and convert to data frame
data = {'x':['a','b','c','d'], 'y':[4,5,6, np.nan]}

In [351]:
data

{'x': ['a', 'b', 'c', 'd'], 'y': [4, 5, 6, nan]}

In [352]:
type(data)

dict

In [353]:
df = pd.DataFrame(data)
df

,x,y
0,a,4.0
1,b,5.0
2,c,6.0
3,d,NaN


In [354]:
x1 = pd.Series([1,2,3,4,5])
x2 = np.array([-1,9,8,3,0])
y = np.array([0,1,0,1,1])
df = pd.DataFrame({'x1':x1, 'x2':x2, 'y':y})
df.dtypes

x1    int64
x2    int32
y     int32
dtype: object

In [355]:
type(df.y)

pandas.core.series.Series

In [356]:
type(df[['y']])

pandas.core.frame.DataFrame

In [357]:
# create a sample dataframe
data = pd.DataFrame({
    'id':     ['A','B','C','D','E','F','G'],
    'age' :     [ 10, 22, 13, 21, 12, 11, 17],
    'section' : [ 'X', 'Y', 'Z', 'Y', 'Y', 'X', 'X'],
    'city' :    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
    'gender' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'favourite_color' : [ 'red', np.NAN, 'yellow', np.NAN, 'black', 'green', 'red']
})
data

,id,age,section,city,gender,favourite_color
0,A,10,X,Gurgaon,M,red
1,B,22,Y,Delhi,F,NaN
2,C,13,Z,Mumbai,F,yellow
3,D,21,Y,Delhi,M,NaN
4,E,12,Y,Mumbai,M,black
5,F,11,X,Delhi,M,green
6,G,17,X,Mumbai,F,red


In [358]:
data.index

RangeIndex(start=0, stop=7, step=1)

In [359]:
data.set_index(['id'], inplace=True)

In [360]:
# view the data
data

,age,section,city,gender,favourite_color
id,,,,,
A,10,X,Gurgaon,M,red
B,22,Y,Delhi,F,NaN
C,13,Z,Mumbai,F,yellow
D,21,Y,Delhi,M,NaN
E,12,Y,Mumbai,M,black
F,11,X,Delhi,M,green
G,17,X,Mumbai,F,red


In [361]:
data['age'], data[['age','city']]

(id
 A    10
 B    22
 C    13
 D    21
 E    12
 F    11
 G    17
 Name: age, dtype: int64,
     age     city
 id              
 A    10  Gurgaon
 B    22    Delhi
 C    13   Mumbai
 D    21    Delhi
 E    12   Mumbai
 F    11    Delhi
 G    17   Mumbai)

In [362]:
data.city.values

array(['Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
      dtype=object)

In [363]:
# while this works, it is not suggested. better ways are .loc and iloc.
data[0:2]

,age,section,city,gender,favourite_color
id,,,,,
A,10,X,Gurgaon,M,red
B,22,Y,Delhi,F,NaN


In [364]:
data.head(5)

,age,section,city,gender,favourite_color
id,,,,,
A,10,X,Gurgaon,M,red
B,22,Y,Delhi,F,NaN
C,13,Z,Mumbai,F,yellow
D,21,Y,Delhi,M,NaN
E,12,Y,Mumbai,M,black


In [365]:
data.tail(1)

,age,section,city,gender,favourite_color
id,,,,,
G,17,X,Mumbai,F,red


# index

• Index Objects,
• Essential functionalities: reindexing,
• dropping entries from an index,
• indexing, selection, and filtering,

In [366]:
x1 = pd.Series([1,2,3,4,5])
x2 = np.array([-1,9,8,3,0])
y = np.array([0,1,0,1,1])
df = pd.DataFrame({'x1':x1, 'x2':x2, 'y':y})
df

,x1,x2,y
0,1,-1,0
1,2,9,1
2,3,8,0
3,4,3,1
4,5,0,1


In [367]:
# query the index object
df.index

RangeIndex(start=0, stop=5, step=1)

In [368]:
# subscriptable but immutable
df.index[0:3]

RangeIndex(start=0, stop=3, step=1)

In [369]:
# set_index() is used to create index using a col or a set of cols
# inplace() makes the changes in the same variable. try True and seeing df.
# by choosing drop=False the column is retained as a data column also. 
# Remove drop and see.

df.set_index('x2',inplace=False, drop=False)

,x1,x2,y
x2,,,
-1,1,-1,0
9,2,9,1
8,3,8,0
3,4,3,1
0,5,0,1


In [370]:
df # original variable is not changed since inplace was False.

,x1,x2,y
0,1,-1,0
1,2,9,1
2,3,8,0
3,4,3,1
4,5,0,1


In [371]:
df.loc[0:2,['x1','x2']]

,x1,x2
0,1,-1
1,2,9
2,3,8


In [372]:
df.iloc[0:2,:]

,x1,x2,y
0,1,-1,0
1,2,9,1


In [373]:
# create an index object from a list and use it to index df
# there are duplicate indexes. if verify_integrity=True it will disallow this. 
indx = pd.Index([11,11,33,44,55])
df_dupl_index = df.set_index(indx, inplace=False, verify_integrity=False)
df_dupl_index.loc[11]

,x1,x2,y
11,1,-1,0
11,2,9,1


In [374]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [375]:
# set index of df
df.index = [-1,0,3,8,9]

In [376]:
df.index

Int64Index([-1, 0, 3, 8, 9], dtype='int64')

In [377]:
df.index = ['f','b',1,'d','e'] # it is not forcing us to use an order bcos...

In [378]:
# index is also rownames
df

,x1,x2,y
f,1,-1,0
b,2,9,1
1,3,8,0
d,4,3,1
e,5,0,1


In [379]:
df.loc[['d','e','f'],:]

,x1,x2,y
d,4,3,1
e,5,0,1
f,1,-1,0


In [380]:
df.loc["f":1,["x1","x2"]]

,x1,x2
f,1,-1
b,2,9
1,3,8


In [381]:
df.index

Index(['f', 'b', 1, 'd', 'e'], dtype='object')

In [382]:
# can index col have duplicates?
# if verify_integrity=True, then it has to be unique. else duplicates are allowed.

In [383]:
df.index = [1,2,3,4,5]
df

,x1,x2,y
1,1,-1,0
2,2,9,1
3,3,8,0
4,4,3,1
5,5,0,1


In [384]:
# this can be used to get rows, using the row label or names
df.loc[1]

x1    1
x2   -1
y     0
Name: 1, dtype: int64

In [385]:
df.loc[1:3] # this fetches rownames 1,2

,x1,x2,y
1,1,-1,0
2,2,9,1
3,3,8,0


In [386]:
# all rows, and a specific column
type(df.loc[:,['x1']])

pandas.core.frame.DataFrame

In [387]:
# all rows, and a slected columns
df.loc[:,['x1','x2']]

,x1,x2
1,1,-1
2,2,9
3,3,8
4,4,3
5,5,0


In [388]:
# some rows and some columns
df.loc[1:3,['x1','x2']]

,x1,x2
1,1,-1
2,2,9
3,3,8


In [389]:
df

,x1,x2,y
1,1,-1,0
2,2,9,1
3,3,8,0
4,4,3,1
5,5,0,1


In [390]:
# this makes the index as a regular col
df.reset_index(drop=False)
# try making drop=True

,index,x1,x2,y
0,1,1,-1,0
1,2,2,9,1
2,3,3,8,0
3,4,4,3,1
4,5,5,0,1


In [391]:
# inplace makes the changes in the original df itself
df.reset_index(drop=True, inplace=True)

In [392]:
df

,x1,x2,y
0,1,-1,0
1,2,9,1
2,3,8,0
3,4,3,1
4,5,0,1


In [393]:
df.set_index(x1, drop=True)

,x1,x2,y
1,1,-1,0
2,2,9,1
3,3,8,0
4,4,3,1
5,5,0,1


In [394]:
df.set_index('x1',drop=True)

,x2,y
x1,,
1,-1,0
2,9,1
3,8,0
4,3,1
5,0,1


# loc and iloc
loc uses names to ref to col and rows
iloc uses index to ref to col and rows

In [395]:
data

,age,section,city,gender,favourite_color
id,,,,,
A,10,X,Gurgaon,M,red
B,22,Y,Delhi,F,NaN
C,13,Z,Mumbai,F,yellow
D,21,Y,Delhi,M,NaN
E,12,Y,Mumbai,M,black
F,11,X,Delhi,M,green
G,17,X,Mumbai,F,red


In [396]:
data.iloc[:,[-2,-1]]

,gender,favourite_color
id,,
A,M,red
B,F,NaN
C,F,yellow
D,M,NaN
E,M,black
F,M,green
G,F,red


In [397]:
data.loc['A']

age                     10
section                  X
city               Gurgaon
gender                   M
favourite_color        red
Name: A, dtype: object

In [398]:
# all rows, column named 'age'
data.loc[:,['age','city']]

,age,city
id,,
A,10,Gurgaon
B,22,Delhi
C,13,Mumbai
D,21,Delhi
E,12,Mumbai
F,11,Delhi
G,17,Mumbai


In [399]:
data.index # this sets name of the index column to 'id'

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object', name='id')

In [400]:
# select rows, columns named 'age' and 'city'
data.loc[['A','B','C'],['age','city']]

,age,city
id,,
A,10,Gurgaon
B,22,Delhi
C,13,Mumbai


In [401]:
data

,age,section,city,gender,favourite_color
id,,,,,
A,10,X,Gurgaon,M,red
B,22,Y,Delhi,F,NaN
C,13,Z,Mumbai,F,yellow
D,21,Y,Delhi,M,NaN
E,12,Y,Mumbai,M,black
F,11,X,Delhi,M,green
G,17,X,Mumbai,F,red


In [402]:
data.iloc[0], data.loc['A']

(age                     10
 section                  X
 city               Gurgaon
 gender                   M
 favourite_color        red
 Name: A, dtype: object,
 age                     10
 section                  X
 city               Gurgaon
 gender                   M
 favourite_color        red
 Name: A, dtype: object)

In [409]:
for i in np.arange(data.shape[1]):
    print(list(data.iloc[:,i])) 

[10, 22, 13, 21, 12, 11, 17]
['X', 'Y', 'Z', 'Y', 'Y', 'X', 'X']
['Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai']
['M', 'F', 'F', 'M', 'M', 'M', 'F']
['red', nan, 'yellow', nan, 'black', 'green', 'red']


In [414]:
for i in data.columns:
    print("Now dropping column:",i)
    print([data.drop(i,axis=1)])

Now dropping column: age
[   section     city gender favourite_color
id                                        
A        X  Gurgaon      M             red
B        Y    Delhi      F             NaN
C        Z   Mumbai      F          yellow
D        Y    Delhi      M             NaN
E        Y   Mumbai      M           black
F        X    Delhi      M           green
G        X   Mumbai      F             red]
Now dropping column: section
[    age     city gender favourite_color
id                                     
A    10  Gurgaon      M             red
B    22    Delhi      F             NaN
C    13   Mumbai      F          yellow
D    21    Delhi      M             NaN
E    12   Mumbai      M           black
F    11    Delhi      M           green
G    17   Mumbai      F             red]
Now dropping column: city
[    age section gender favourite_color
id                                    
A    10       X      M             red
B    22       Y      F             NaN
C    13     

In [81]:
data

,age,section,city,gender,favourite_color
id,,,,,
A,10,X,Gurgaon,M,red
B,22,Y,Delhi,F,NaN
C,13,Z,Mumbai,F,yellow
D,21,Y,Delhi,M,NaN
E,12,Y,Mumbai,M,black
F,11,X,Delhi,M,green
G,17,X,Mumbai,F,red


In [89]:
data.loc[:,-1]

id
A       red
B       NaN
C    yellow
D       NaN
E     black
F     green
G       red
Name: favourite_color, dtype: object

In [67]:
# all rows of age column
data.iloc[:,0]

id
A    10
B    22
C    13
D    21
E    12
F    11
G    17
Name: age, dtype: int64

In [68]:
# select rows, columns age and city
data.iloc[0:3,[0,2] ]

,age,city
id,,
A,10,Gurgaon
B,22,Delhi
C,13,Mumbai


In [69]:
data.iloc[[0,1],[0,3]]

,age,gender
id,,
A,10,M
B,22,F


In [70]:
# how to select discontinuous set of index elements?
# for e.g. [0:3] is continuous. what if we want first 3, 5-9 etc.


# np.r_ concatenates a set of indexes that can be used inside iloc

In [71]:
arr = np.array([15,0,8,1,9,4,7])

In [72]:
arr[np.r_[2,3,-2]]

array([8, 1, 4])

In [73]:
data.iloc[np.r_[0:2,3],np.r_[2,4]]

,city,favourite_color
id,,
A,Gurgaon,red
B,Delhi,NaN
D,Delhi,NaN


In [74]:
p_rollno = pd.Series([1,2,3,4,5])
p_names = pd.Series(['A','B','C','D','E'])
p_marks = pd.Series([89,90,76,85,99])

q_rollno = pd.Series([1,2,3,4,5])
q_names = pd.Series(['A','B','C','D','E'])
q_marks = pd.Series([89,90,76,85,99])

In [75]:
df_p = pd.DataFrame({'roll':p_rollno,'name':p_names,'marks':p_marks})
df_p

,roll,name,marks
0,1,A,89
1,2,B,90
2,3,C,76
3,4,D,85
4,5,E,99


In [76]:
df_q = pd.DataFrame({'roll':q_rollno,'name':q_names,'marks':q_marks})
df_q

,roll,name,marks
0,1,A,89
1,2,B,90
2,3,C,76
3,4,D,85
4,5,E,99


In [77]:
df_p['marks'] + df_q['marks']

0    178
1    180
2    152
3    170
4    198
Name: marks, dtype: int64

In [78]:
new_student = {'roll':[6],'name':['F'],'marks':[90]}
new_row = pd.DataFrame(new_student)

In [79]:
df_q = df_q.append(pd.DataFrame(new_student),ignore_index = True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
df_q

,roll,name,marks
0,1,A,89
1,2,B,90
2,3,C,76
3,4,D,85
4,5,E,99
5,6,F,90


In [ ]:
df_p['marks'] + df_q['marks']

0    178.0
1    180.0
2    152.0
3    170.0
4    198.0
5      NaN
Name: marks, dtype: float64

In [ ]:
df_p['marks'].add(df_q['marks'],fill_value=0)

0    178.0
1    180.0
2    152.0
3    170.0
4    198.0
5     90.0
Name: marks, dtype: float64

# Function application and mapping

In [ ]:
seris = pd.Series(np.random.normal(size=100))

In [ ]:
seris.mean(), seris.median(), seris.min(), seris.quantile(0.12)

(0.10171022019386892,
 0.11569081340653983,
 -3.00913319979208,
 -0.8665409339132801)

In [ ]:
df.max()

x1    5
x2    9
y     1
dtype: int64

In [ ]:
# numpy functions work on pandas objects
df_p.marks.min(), df_p.marks.max()

(76, 99)

In [ ]:
def range_of(arr):
    return [arr.max(), arr.min()]

In [ ]:
range_of(df.x1), range_of(df.x2), range_of(df.y)

([5, 1], [9, -1], [1, 0])

In [ ]:
df.apply(range_of)

,x1,x2,y
0,5,9,1
1,1,-1,0


# sorting and ranking

In [90]:
df = pd.DataFrame(np.random.randint(low=0,high=10,size=15).reshape(5,3), columns=['X1','X2','X3'])
df

,X1,X2,X3
0,9,0,5
1,0,9,7
2,5,9,9
3,7,8,3
4,1,2,9


In [91]:
df.sort_values(by='X1')

,X1,X2,X3
1,0,9,7
4,1,2,9
2,5,9,9
3,7,8,3
0,9,0,5


In [ ]:
df.sort_values(by=['X1','X2'])

,X1,X2,X3
0,4,5,8
2,5,3,1
4,9,0,8
3,9,5,7
1,9,8,4


In [ ]:
# ranking
df

,X1,X2,X3
0,4,5,8
1,9,8,4
2,5,3,1
3,9,5,7
4,9,0,8


In [ ]:
marks = pd.Series([100,25,75])
marks, marks.rank(ascending=False)

(0    100
 1     25
 2     75
 dtype: int64,
 0    1.0
 1    3.0
 2    2.0
 dtype: float64)

In [ ]:
# gives rank of the rows.tie breaking options are available.
ranx = df['X1'].rank()

In [ ]:
df[ranx < 3]

,X1,X2,X3
0,4,5,8
2,5,3,1


# Summarizing and Computing Descriptive Statistics

In [ ]:
# generate summary statistics from a dataframe

In [ ]:
df.mean()

X1    7.2
X2    4.2
X3    5.6
dtype: float64

In [ ]:
# try df.median(), max, min, std, var

In [ ]:
df.max(axis=0)

X1    9
X2    8
X3    8
dtype: int32

In [ ]:
df.max(axis=1)

0    8
1    9
2    5
3    9
4    9
dtype: int32

In [ ]:
df.describe()

,X1,X2,X3
count,5.00000,5.000000,5.00000
mean,7.20000,4.200000,5.60000
std,2.48998,2.949576,3.04959
min,4.00000,0.000000,1.00000
25%,5.00000,3.000000,4.00000
50%,9.00000,5.000000,7.00000
75%,9.00000,5.000000,8.00000
max,9.00000,8.000000,8.00000


In [ ]:
df.X1.std(), df.X1.std(ddof=0)

(2.4899799195977463, 2.2271057451320084)

In [ ]:
np.std(df.X1), np.std(df.X1, ddof=1)

(2.2271057451320084, 2.4899799195977463)

In [ ]:
df.corr()

,X1,X2,X3
X1,1.000000,0.027232,0.210709
X2,0.027232,1.000000,-0.211228
X3,0.210709,-0.211228,1.000000


In [ ]:
df.cov(ddof=1)

,X1,X2,X3
X1,6.2,0.2,1.6
X2,0.2,8.7,-1.9
X3,1.6,-1.9,9.3


In [ ]:
df.X1.unique()

array([4, 9, 5])

In [ ]:
df.X2.value_counts()

5    2
8    1
3    1
0    1
Name: X2, dtype: int64

In [ ]:
# read dataset.csv
df = pd.read_csv('dataset.csv')

# missing values

In [ ]:
df.isna().sum(axis=0)/df.shape[0]

X1    0.04
X2    0.02
X3    0.04
X4    0.00
X5    0.04
X6    0.02
X7    0.02
dtype: float64

In [ ]:
df.isna().sum()/df.shape[0] * 100

X1    4.0
X2    2.0
X3    4.0
X4    0.0
X5    4.0
X6    2.0
X7    2.0
dtype: float64

In [ ]:
# checking for missing values in each column
df.isna().sum()

X1    2
X2    1
X3    2
X4    0
X5    2
X6    1
X7    1
dtype: int64

In [ ]:
# fill na with mean
df.fillna(value=df.mean()).head()

,X1,X2,X3,X4,X5,X6,X7
0,-0.791878,17.167626,5.841274,5.220455,18.523899,18.663697,4.041688
1,17.427310,13.846494,9.888121,23.756874,-0.342502,13.803442,3.547032
2,4.632233,2.124638,-0.229236,10.231537,14.421863,6.417859,-2.659034
3,13.578017,17.849467,7.825274,18.197271,7.403954,-1.620997,-2.068353
4,-1.579972,4.126381,18.258094,4.865118,23.459287,14.608267,9.506448


In [ ]:
# trim df for compact display
df = df[['X1','X2','X3','X4','X5']].head(10)

In [ ]:
# take a column level approach
df['X1'].fillna(value=df.X1.mean())

0    -0.791878
1    17.427310
2     4.632233
3    13.578017
4    -1.579972
5    13.971940
6    23.905105
7    -1.099703
8    24.740277
9    20.798601
Name: X1, dtype: float64

In [ ]:
# selection of columns level approach
df[['X1','X2']].fillna(value=df[['X1','X2']].mean())

,X1,X2
0,-0.791878,17.167626
1,17.427310,13.846494
2,4.632233,2.124638
3,13.578017,17.849467
4,-1.579972,4.126381
5,13.971940,-2.824147
6,23.905105,9.566466
7,-1.099703,14.575360
8,24.740277,-0.711492
9,20.798601,2.344932


# add col, drop col, drop drop rows, add rows to dataframe

In [ ]:
# add new column to an existing df

In [ ]:
df.shape

(10, 5)

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
df['ones'] = np.ones(df.shape[0])
df

,X1,X2,X3,X4,X5,ones
0,-0.791878,17.167626,5.841274,5.220455,18.523899,1.0
1,17.427310,13.846494,9.888121,23.756874,-0.342502,1.0
2,4.632233,2.124638,-0.229236,10.231537,14.421863,1.0
3,13.578017,17.849467,7.825274,18.197271,7.403954,1.0
4,-1.579972,4.126381,18.258094,4.865118,23.459287,1.0
5,13.971940,-2.824147,21.300136,2.892762,-0.435163,1.0
6,23.905105,9.566466,NaN,17.423095,6.974111,1.0
7,-1.099703,14.575360,-4.372999,13.299024,8.886915,1.0
8,24.740277,-0.711492,4.327235,18.428205,4.533996,1.0
9,20.798601,2.344932,14.850875,17.971490,8.175363,1.0


In [ ]:
df['X_new'] = [1,2,1,2,3,1,2,1,2,3]
df

,X1,X2,X3,X4,X5,X_new
0,-0.791878,17.167626,5.841274,5.220455,18.523899,1
1,17.427310,13.846494,9.888121,23.756874,-0.342502,2
2,4.632233,2.124638,-0.229236,10.231537,14.421863,1
3,13.578017,17.849467,7.825274,18.197271,7.403954,2
4,-1.579972,4.126381,18.258094,4.865118,23.459287,3
5,13.971940,-2.824147,21.300136,2.892762,-0.435163,1
6,23.905105,9.566466,NaN,17.423095,6.974111,2
7,-1.099703,14.575360,-4.372999,13.299024,8.886915,1
8,24.740277,-0.711492,4.327235,18.428205,4.533996,2
9,20.798601,2.344932,14.850875,17.971490,8.175363,3


In [ ]:
df.sort_values(by=['X1','X2'],ascending=[True,False])

,X1,X2,X3,X4,X5,X_new
4,-1.579972,4.126381,18.258094,4.865118,23.459287,3
7,-1.099703,14.575360,-4.372999,13.299024,8.886915,1
0,-0.791878,17.167626,5.841274,5.220455,18.523899,1
2,4.632233,2.124638,-0.229236,10.231537,14.421863,1
3,13.578017,17.849467,7.825274,18.197271,7.403954,2
5,13.971940,-2.824147,21.300136,2.892762,-0.435163,1
1,17.427310,13.846494,9.888121,23.756874,-0.342502,2
9,20.798601,2.344932,14.850875,17.971490,8.175363,3
6,23.905105,9.566466,NaN,17.423095,6.974111,2
8,24.740277,-0.711492,4.327235,18.428205,4.533996,2


In [ ]:
# drop a column
df.drop('X_new',axis='columns')

,X1,X2,X3,X4,X5
0,-0.791878,17.167626,5.841274,5.220455,18.523899
1,17.427310,13.846494,9.888121,23.756874,-0.342502
2,4.632233,2.124638,-0.229236,10.231537,14.421863
3,13.578017,17.849467,7.825274,18.197271,7.403954
4,-1.579972,4.126381,18.258094,4.865118,23.459287
5,13.971940,-2.824147,21.300136,2.892762,-0.435163
6,23.905105,9.566466,NaN,17.423095,6.974111
7,-1.099703,14.575360,-4.372999,13.299024,8.886915
8,24.740277,-0.711492,4.327235,18.428205,4.533996
9,20.798601,2.344932,14.850875,17.971490,8.175363


In [ ]:
# drop multiple columns
df.drop(['X5','X_new'],axis=1)

In [ ]:
# no need for axis in this case
df.drop(columns=['X5','X_new'])

In [ ]:
df.drop([0,1,5,9])

In [ ]:
frm=5
upto=40
df.drop(df.loc[frm:upto].index)

In [ ]:
df.columns

In [ ]:
df1 = df[['X1','X2','X3']].head(5)
df1.shape

In [ ]:
df1

In [ ]:
# append rows to df1

for i in np.arange(3):
    # generate random numbers matching the col count
    rnd = np.random.randint(low=0,high=10,size=3)
    rowdict = {'X1':rnd[0], 'X2':rnd[1], 'X3':rnd[2]}
    df1 = df1.append(rowdict, ignore_index=True)

In [ ]:
df1

In [ ]:
df1.reindex()

In [ ]:
# append and reindex

In [ ]:
q_rollno = pd.Series([1,2,3,4,5])
q_names = pd.Series(['A','B','C','D','E'])
q_marks = pd.Series([89,90,76,85,99])

In [ ]:
df_q = pd.DataFrame({'roll':q_rollno, 'names':q_names, 'marks':q_marks})

In [ ]:
df_q.index = ['a','b','c','d','e']

In [ ]:
new_row = {'roll':[15], 'names':['W'], 'marks':[99]}

In [ ]:
pd.DataFrame(new_row, index=['f'])

In [ ]:
df_q = df_q.append(pd.DataFrame(new_row, index=['f']))

In [ ]:
df_q.index

In [ ]:
df_q.reindex()